### ISSUE TITLE
Nav Buttons

### ISSUE THREAD

**Issue by Yasin-Goenendi** [Yasin-Goenendi/capstone-project#2]
## Value Proposition

- As an user 
- I want buttons for home, search, watched
and favourite 
- So that i can switch from my Homescreen
​

## Description

​
<img width="325" alt="Bildschirm­foto 2023-03-03 um 14 26 37" src="https://user-images.githubusercontent.com/121627582/222731882-22723146-4344-44ec-b4de-9d580c37d2ff.png">

## Acceptance Criteria

 - [ ]  All buttons are displayed
 - [ ]  clicking a button will take you to the folder from each button
      ​

## Tasks

- [ ] create a branch 
- [ ] create Components for each button
- [ ] create a onClick Event on every button
- [ ] route the pages on next.js
      ​
