### ISSUE TITLE
Film Info

### ISSUE THREAD

**Issue by Yasin-Goenendi** [Yasin-Goenendi/capstone-project#4]
## Value Proposition

As an user
I want a detail information for each films
So that i can  the picture and the description
​

## Description

<img width="462" alt="Bildschirm­foto 2023-03-03 um 16 09 41" src="https://user-images.githubusercontent.com/121627582/222755750-0942154f-66d7-4143-8f3f-c316cb3f36ab.png">

​

## Acceptance Criteria

- [ ] Clicking a film shows the detail page
- [ ] the film Titel, the description and the picture are displayed
- [ ] the buttons below are displayed 
      ​

## Tasks

- [ ] create a branch
- [ ] create a Component names FilmDetails
- [ ] take info from film API
      ​

**Comment by MelissaDuve** [comment]
👌
