### ISSUE TITLE
Toggle function

### ISSUE THREAD

**Issue by Yasin-Goenendi** [Yasin-Goenendi/capstone-project#5]
## Value Proposition

As a User  
I want a buttons
so that i can like and mark my films
​

## Description

<img width="396" alt="Bildschirm­foto 2023-03-04 um 19 27 19" src="https://user-images.githubusercontent.com/121627582/222923030-53b836cd-31d4-4ff8-bce7-7aa81b18cca6.png">

​

## Acceptance Criteria

- [ ] the like button is displayed when you click 
- [ ] the watched button is displayed when you click it
- [ ] when you click the like button, the film goes to the favourite folder
- [ ] when you clicked watched, the film goes to the watched folder
      ​

## Tasks

- [ ] create a branch
- [ ] create a onClick "Toggle" event on each button
- [ ] route the pages on next.js
      ​
